Python/EXOS/README.md
=> Readme Change

EXOS/CLI_Scripting/disablefaultedpoe/README.md, EXOS/CLI_Scripting/disablefaultedpoe/disablefaultedpoe.xsf, EXOS/CLI_Scripting/poeupmdisable/README.md, EXOS/CLI_Scripting/poeupmdisable/poe_upm.xsf
Added two scripts for handling legacy inline-power and faulted ports
=> PoE scripts

EXOS/Python/README.md, EXOS/Python/mlag_config_check/README.md, EXOS/Python/mlag_config_check/mlag_config_check.py
Also updated README to include this script.
=> Added MLAG config check script

EXOS/Python/watch/README.md, EXOS/Python/watch/watch.py
Added watch.py and associated README
=> Added watch.py

EXOS/Python/mlag_config_check/README.md, EXOS/Python/mlag_config_check/mlag_config_check.py
Added FDB checksum checking between MLAG peers.
=> Updated MLAG config check

EXOS/Python/snmpassist/README.md, EXOS/Python/snmpassist/snmpassist.py
Added privacy/encryption options and file cleanup.
=> snmpassist changes

EXOS/Python/snmpassist/snmpassist.py
Since 16.2 has the ssh xmod built in, I updated the script so the
script will check to see if 16.2 is installed. If it is, the script
will enable SSH2 if AES or 3DES privacy are selected
=> inclusion of 16.2

EXOS/Python/README.md, EXOS/Python/dhcp43/README.md, EXOS/Python/dhcp43/dhcp43.py
Added a script to automate configuration of EXOS DHCP server for ZTP
option 43
=> Added dhcp43.py

EXOS/CLI_Scripting/autoneg-halfduplex/README.md, EXOS/CLI_Scripting/autoneg-halfduplex/autoNeg.xsf
Script to assist customers with original G2 models with discovering and configuring legacy half duplex devices so that they will link up and work.
=> Auto Negotiation Half Duplex G2

README.md, SLX_EventHandler/README.MD, SLX_EventHandler/event_handler_template.py, SLX_EventHandler/po_member.py
Contains a template and an example
=> Adding in the SLX_Eventhandler

Netsight/nbi_clients/GenericNbiClient.py/GenericNbiClient.py, Netsight/nbi_clients/GenericNbiClient.py/LICENSE, Netsight/nbi_clients/GenericNbiClient.py/README.md, Netsight/nbi_clients/README.md
As the title says: Python variant of GenericNbiClient, for those who are more comfortable with Python than Go.
=> Add Python variant of GenericNbiClient.

Netsight/README.md, Netsight/nbi_clients/GenericNbiClient.go/GenericNbiClient.go, Netsight/nbi_clients/GenericNbiClient.go/README.md, Netsight/nbi_clients/GenericNbiClient.py/README.md, Netsight/nbi_clients/README.md
Includes improved functionality and bugfixes.
=> Bump GenericNbiClient.go to v0.8.0

Netsight/README.md, Netsight/nbi_clients/GenericNbiClient.go/GenericNbiClient.go, Netsight/nbi_clients/GenericNbiClient.go/LICENSE, Netsight/nbi_clients/GenericNbiClient.go/README.md, Netsight/nbi_clients/README.md, README.md
The new version is based on a module that handles the NBI interaction. Attention: CLI arguments have been changed.
=> Bump GenericNbiClient.go to v0.10.0

EXOS/Python/post_dom_data_exos30_vrf/README.md
As requested in the already-merged PR #59, added a README file for the script.
=> Add README for post_dom_data_exos30_vrf

Cloud_Appliance/README.md, Cloud_Appliance/REST_Clients/BssidLister/BssidLister.go, Cloud_Appliance/REST_Clients/BssidLister/LICENSE, Cloud_Appliance/REST_Clients/BssidLister/README.md, Cloud_Appliance/REST_Clients/README.md, README.md
Added new section for ExtremeCloud Appliance. Within this section, the application BssidLister has been added; it is a Go rewrite of [a Python script provided by GTAC](https://gtacknowledge.extremenetworks.com/articles/How_To/How-can-I-retrieve-a-list-of-BSSIDs-from-an-XCA-controller-using-the-REST-API/).
=> Added new section XCA and application BssidLister.

Cloud_IQ/README.md, Cloud_IQ/REST_Clients/BssidLister/BssidLister.go, Cloud_IQ/REST_Clients/BssidLister/LICENSE, Cloud_IQ/REST_Clients/BssidLister/README.md, Cloud_IQ/REST_Clients/README.md, README.md
Another new section, this time for ExtremeCloud IQ utilities. Includes working BssidLister variant for XIQ.
=> Add new section XIQ and application BssidLister

Cloud_Appliance/REST_Clients/BssidLister/BssidLister.go, Cloud_Appliance/REST_Clients/BssidLister/README.md
The new version's output is way more detailed.
=> Bump XCA BssidLister to v0.3.0.

Netsight/nbi_clients/GenericNbiClient.go/GenericNbiClient.go, Netsight/nbi_clients/GenericNbiClient.go/README.md
=> Update GenericNbiClient.go to latest version 0.12.0.

Netsight/nbi_clients/README.md, Netsight/nbi_clients/VlanLister.go/LICENSE, Netsight/nbi_clients/VlanLister.go/README.md, Netsight/nbi_clients/VlanLister.go/VlanLister_main.go, Netsight/nbi_clients/VlanLister.go/VlanLister_queries.go, Netsight/nbi_clients/VlanLister.go/VlanLister_writers.go, Netsight/nbi_clients/VlanLister.go/VlanLister_xmcclient.go
VlanLister.go utilizes the XMC NBI to fetch the complete list of port/VLAN associations and stores the result as a CSV and/or XLSX file.
=> Add new tool VlanLister.go.

Cloud_IQ/API_2021/Python/XIQ.py, XMC_XIQ-SE/nbi_clients/Python3/XMC_NBI.py, XMC_XIQ-SE/nbi_clients/Python3/get_MAC.py, XMC_XIQ-SE/nbi_clients/Python3/get_devicese.py, XMC_XIQ-SE/nbi_clients/Python3/manage_MAC.py, XMC_XIQ-SE/nbi_clients/Python3/query.py, XMC_XIQ-SE/nbi_clients/Python3/simple.py, XMC_XIQ-SE/nbi_clients/Python3/site_export.py, XMC_XIQ-SE/nbi_clients/Python3/site_import.py, XMC_XIQ-SE/nbi_clients/README.md
update class as well example scripts. Provide additional examples.
=> update XMC-NBI class
